# ETL

In [1]:
import pandas as pd
import os
from scripts.georef import add_unidades_territoriales_to_df

## Carga de inputs

In [2]:
#file
df_alumnos = pd.read_csv('data/input/alumnos.csv',delimiter=',')
df_carreras = pd.read_csv('data/input/carreras.csv',delimiter=',')

if os.path.exists('data/output/universidades.csv'):
    df_universidades = pd.read_csv('data/output/universidades.csv',delimiter=',',dtype={"provincia_id":str})
else:
    df_universidades_raw = pd.read_csv('data/input/universidades.csv',delimiter=',')
    df_universidades_raw["lat"] = df_universidades_raw['coordenadas'].str.split(",").str[0]
    df_universidades_raw["lon"] = df_universidades_raw['coordenadas'].str.split(",").str[1]
    df_universidades = add_unidades_territoriales_to_df(df_universidades_raw, lat_col="lat", lon_col="lon")
    df_universidades.to_csv('data/output/universidades.csv', sep=',', encoding='utf8', index=False)

In [3]:
df_alumnos = df_alumnos[df_alumnos.anio != 2010]

In [4]:
#Universidades consistentes

In [5]:
universidad_anio = df_alumnos[["institucion_nombre",'anio']].drop_duplicates()
universidad_anio_count = universidad_anio.groupby(["institucion_nombre"]).count()

In [6]:
lista_universidades = universidad_anio_count[universidad_anio_count.anio == 7].index

In [7]:
df_alumnos = df_alumnos[df_alumnos.institucion_nombre.isin(lista_universidades)]

## Exporacion

In [8]:
df_carreras.head(10)

,carrera,carrera_grupo,Carrera_normalizada
0,Abogado,Derecho,Abogacia
1,Abogado - Ciclo de Complementacion Curricular,Derecho,Abogacia
2,Abogado - MD,Derecho,Abogacia
3,Abogado Especialista en Administración de Just...,Derecho,Abogacia
4,Abogado especialista en Asesoramiento de Empresas,Derecho,Abogacia
5,Abogado Especialista en Asesoria Juridica de E...,Derecho,Abogacia
6,Abogado especialista en Derecho Administrativo...,Derecho,Abogacia
7,Abogado especialista en Derecho Ambiental,Derecho,Abogacia
8,Abogado especialista en Derecho de Alta Tecnol...,Derecho,Abogacia
9,Abogado especialista en Derecho Penal,Derecho,Abogacia

In [9]:
df_alumnos.head(10)

,anio,institucion_tipo,institucion_nombre,institucion_nombre_new,institucion_nombre_unidad_academica,unidad_academica,unidad_academica_new,carrera_nombre,carrera_titulo,institucion_gestion,...,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,reinscriptos_total,reinscriptos_varones,reinscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres
7315,2011,Universidad,Universitá Degli Studi di Bologna,Universitá Degli Studi di Bologna,Universitá Degli Studi di Bologna - Università...,Università Degli Studi di Bologna,Università Degli Studi di Bologna,Relaciones Internacionales,Magister en Relaciones Internacionales Europa ...,Privada,...,54.0,30.0,13.0,17.0,NaN,NaN,NaN,29.0,14.0,15.0
7316,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Ciencia Politica,Doctor en Ciencia Politica,Privada,...,10.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7317,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Ciencia Politica,Licenciatura en Ciencia Politica y Gobierno,Privada,...,39.0,23.0,10.0,13.0,49.0,23.0,26.0,6.0,4.0,2.0
7318,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Ciencia Politica,Magister en Ciencia Politica,Privada,...,18.0,15.0,12.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
7319,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Relaciones Internacionales,Licenciatura en Estudios Internacionales,Privada,...,71.0,35.0,13.0,22.0,75.0,26.0,49.0,28.0,7.0,21.0
7320,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Relaciones Internacionales,Magister en Estudios Internacionales,Privada,...,100.0,34.0,15.0,19.0,NaN,NaN,NaN,9.0,5.0,4.0
7321,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Economía,Departamento de Economía,Economia,Licenciatura en Economía,Privada,...,49.0,42.0,28.0,14.0,117.0,82.0,35.0,36.0,24.0,12.0
7322,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Economía,Departamento de Economía,Economia,Magister en Econometria,Privada,...,18.0,12.0,9.0,3.0,NaN,NaN,NaN,1.0,NaN,1.0
7323,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Economía,Departamento de Economía,Economia,Magister en Economía,Privada,...,14.0,25.0,20.0,5.0,NaN,NaN,NaN,2.0,2.0,NaN
7324,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Historia,Departamento de Historia,Historia,Doctor en Historia,Privada,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0

In [10]:
df_universidades.head(10)

,universidad_nombre,institucion_nombre,institucion_direccion,api,coordenadas,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,lat,lon,departamento_id,departamento_nombre,latitud,longitud,municipio_id,municipio_nombre,provincia_id,provincia_nombre
0,Escuela Universitaria de Teologia,Escuela Universitaria de Teologia,Pasaje Catedral 1750,NaN,"-36.4494181,-57.7686044",NaN,NaN,NaN,NaN,NaN,...,-36.449418,-57.768604,6238.0,Dolores,-36.449418,-57.768604,60238.0,Dolores,06,Buenos Aires
1,Facultad Latinoamericana de Ciencias Sociales,Facultad Latinoamericana de Ciencias Sociales,Tucumán 1966,NaN,"-34.6021735,-58.3972997",NaN,NaN,NaN,NaN,NaN,...,-34.602173,-58.397300,2021.0,Comuna 3,-34.602173,-58.397300,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
2,Instituto Tecnológico de Buenos Aires,Instituto Tecnológico de Buenos Aires,Av. Eduardo Madero 399,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6028340446427,-58.368183272295",NaN,NaN,NaN,NaN,NaN,...,-34.602834,-58.368183,2007.0,Comuna 1,-34.602834,-58.368183,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
3,Instituto Universitario Aeronáutico,Instituto Universitario Aeronáutico,Av. Fuerza Aerea Argentina 6500,http://apis.datos.gob.ar/georef/api/direccione...,"-31.4337174,-64.2779779",NaN,NaN,NaN,NaN,NaN,...,-31.433717,-64.277978,14014.0,Capital,-31.433717,-64.277978,140077.0,Córdoba,14,Córdoba
4,Instituto Universitario CEMIC,Instituto Universitario CEMIC,Valdenegro 4337,NaN,"-34.5547176,-58.4972877",NaN,NaN,NaN,NaN,NaN,...,-34.554718,-58.497288,2084.0,Comuna 12,-34.554718,-58.497288,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
5,Instituto Universitario de Ciencias Biomedicas...,Instituto Universitario de Ciencias Biomedicas...,Naciones Unidas 400-440,NaN,"-31.4421202,-64.2033758",NaN,NaN,NaN,NaN,NaN,...,-31.442120,-64.203376,14014.0,Capital,-31.442120,-64.203376,140077.0,Córdoba,14,Córdoba
6,Instituto Universitario de Ciencias de la Salu...,Instituto Universitario de Ciencias de la Salu...,Av. Gral. Las Heras 1907,NaN,"-34.5951617,-58.4021427",NaN,NaN,NaN,NaN,NaN,...,-34.595162,-58.402143,2014.0,Comuna 2,-34.595162,-58.402143,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
7,Instituto Universitario de Gendarmeria Nacional,Instituto Universitario de Gendarmeria Nacional,Av. Paseo Colón 533,NaN,"-34.6142528,-58.371724",NaN,NaN,NaN,NaN,NaN,...,-34.614253,-58.371724,2007.0,Comuna 1,-34.614253,-58.371724,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
8,Instituto Universitario de la Policía Federal ...,Instituto Universitario de la Policía Federal ...,Rosario 532,NaN,"-34.6196133,-58.4382653",NaN,NaN,NaN,NaN,NaN,...,-34.619613,-58.438265,2042.0,Comuna 6,-34.619613,-58.438265,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
9,Instituto Universitario de Salud Mental de la ...,Instituto Universitario de Salud Mental de la ...,Báez 248,NaN,"-34.567895,-58.4361568",NaN,NaN,NaN,NaN,NaN,...,-34.567895,-58.436157,2098.0,Comuna 14,-34.567895,-58.436157,NaN,NaN,02,Ciudad Autónoma de Buenos Aires

## Calculo evolucion de genero en carreras

In [11]:
df_alumnos_merged = df_alumnos.merge(df_carreras, how="left", left_on="carrera_titulo", right_on="carrera")

In [12]:
col_nulls = df_alumnos_merged.isnull().any()
col_nulls

anio                                   False
institucion_tipo                       False
institucion_nombre                     False
institucion_nombre_new                 False
institucion_nombre_unidad_academica    False
unidad_academica                       False
unidad_academica_new                   False
carrera_nombre                         False
carrera_titulo                         False
institucion_gestion                    False
carrera_titulo_nivel                   False
Modalidad                              False
estudiantes_total                       True
estudiantes_varones                     True
estudiantes_mujeres                     True
nuevos_inscriptos_total                 True
nuevos_inscriptos_varones               True
nuevos_inscriptos_mujeres               True
reinscriptos_total                      True
reinscriptos_varones                    True
reinscriptos_mujeres                    True
egresados_total                         True
egresados_varones                       True
egresados_mujeres                       True
carrera                                 True
carrera_grupo                           True
Carrera_normalizada                     True
dtype: bool

In [13]:
df_alumnos_merged.carrera_grupo.isnull().value_counts()

False    54081
True      7638
Name: carrera_grupo, dtype: int64

In [14]:
variables = [
    "estudiantes_total","estudiantes_varones","estudiantes_mujeres",
    "nuevos_inscriptos_total","nuevos_inscriptos_varones","nuevos_inscriptos_mujeres",
    "egresados_total","egresados_varones","egresados_mujeres",
]

In [15]:
df_evolucion_carrera = df_alumnos_merged.groupby(["anio","carrera_grupo"]).sum()

In [16]:
df_evolucion_carrera = df_evolucion_carrera[variables]
df_evolucion_carrera = df_evolucion_carrera.reset_index()
#df_evolucion_carrera = df_evolucion_carrera.drop("index",1)

In [17]:
df_evolucion_carrera.head(10)

,anio,carrera_grupo,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres
0,2011,Arquitectura,74050.0,37670.0,36380.0,12644.0,6184.0,6460.0,3862.0,1705.0,2157.0
1,2011,Arte,76817.0,29697.0,47120.0,17846.0,7270.0,10576.0,3354.0,998.0,2356.0
2,2011,Deporte,3308.0,2038.0,1270.0,984.0,660.0,324.0,174.0,107.0,67.0
3,2011,Derecho,241945.0,104181.0,137764.0,54097.0,24557.0,29540.0,16300.0,6926.0,9374.0
4,2011,Economicas,402309.0,184179.0,218130.0,93449.0,44556.0,48893.0,25766.0,11589.0,14177.0
5,2011,Educación,150716.0,40181.0,110535.0,45382.0,13045.0,32337.0,9323.0,2285.0,7038.0
6,2011,Exactas,43627.0,20874.0,22753.0,9174.0,4239.0,4935.0,2551.0,1123.0,1428.0
7,2011,Idiomas,19683.0,4135.0,15548.0,4379.0,939.0,3440.0,787.0,90.0,697.0
8,2011,Ingeniería,105094.0,89425.0,15669.0,21757.0,18181.0,3576.0,4786.0,3953.0,833.0
9,2011,Letras,370.0,68.0,302.0,102.0,24.0,78.0,11.0,0.0,11.0

In [18]:
df_evolucion_carrera["estudiantes_mujeres_pct"] = df_evolucion_carrera.estudiantes_mujeres/df_evolucion_carrera.estudiantes_total
#incriptas como predictor de composicion e interes.
df_evolucion_carrera["inscripciones_mujeres_pct"] = df_evolucion_carrera.nuevos_inscriptos_mujeres/df_evolucion_carrera.nuevos_inscriptos_total
#agregar ratio de hombres
df_evolucion_carrera["estudiantes_hombres_pct"] = df_evolucion_carrera.estudiantes_varones/df_evolucion_carrera.estudiantes_total

In [19]:
df_evolucion_carrera.to_csv("data/output/grupos_evolucion_genero.csv", encoding = "UTF8", index = False)

## Grafico exploratorio

### carreras

In [20]:
df_evolucion_carrera_carreras = df_alumnos_merged.groupby(["anio","carrera_grupo","carrera_nombre"]).sum()

In [21]:
df_evolucion_carrera_carreras = df_evolucion_carrera_carreras[variables]
df_evolucion_carrera_carreras = df_evolucion_carrera_carreras.reset_index()

In [22]:
df_evolucion_carrera_carreras["estudiantes_mujeres_pct"] = df_evolucion_carrera_carreras.estudiantes_mujeres/df_evolucion_carrera_carreras.estudiantes_total
#incriptas como predictor de composicion e interes.
df_evolucion_carrera_carreras["inscripciones_mujeres_pct"] = df_evolucion_carrera_carreras.nuevos_inscriptos_mujeres/df_evolucion_carrera_carreras.nuevos_inscriptos_total
#agregar ratio de hombres
df_evolucion_carrera_carreras["estudiantes_hombres_pct"] = df_evolucion_carrera_carreras.estudiantes_varones/df_evolucion_carrera_carreras.estudiantes_total

In [23]:
df_evolucion_carrera_carreras.to_csv("data/output/grupos_carreras_evolucion_genero.csv", encoding = "UTF8", index = False)

In [24]:
df_evolucion_carrera_universidad = df_alumnos_merged.groupby(["anio","carrera_grupo","institucion_nombre_new"]).sum()

In [25]:
df_evolucion_carrera_universidad = df_evolucion_carrera[variables]
df_evolucion_carrera_universidad = df_evolucion_carrera.reset_index()

In [26]:
df_evolucion_carrera_universidad["estudiantes_mujeres_pct"] = df_evolucion_carrera_universidad.estudiantes_mujeres/df_evolucion_carrera_universidad.estudiantes_total
#incriptas como predictor de composicion e interes.
df_evolucion_carrera_universidad["inscripciones_mujeres_pct"] = df_evolucion_carrera_universidad.nuevos_inscriptos_mujeres/df_evolucion_carrera_universidad.nuevos_inscriptos_total
#agregar ratio de hombres
df_evolucion_carrera_universidad["estudiantes_hombres_pct"] = df_evolucion_carrera_universidad.estudiantes_varones/df_evolucion_carrera_universidad.estudiantes_total

In [27]:
df_evolucion_carrera_universidad.to_csv("data/output/carreras_universidad_evolucion_genero.csv", encoding = "UTF8", index = False)

In [28]:
df_universidades.head()

,universidad_nombre,institucion_nombre,institucion_direccion,api,coordenadas,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,lat,lon,departamento_id,departamento_nombre,latitud,longitud,municipio_id,municipio_nombre,provincia_id,provincia_nombre
0,Escuela Universitaria de Teologia,Escuela Universitaria de Teologia,Pasaje Catedral 1750,NaN,"-36.4494181,-57.7686044",NaN,NaN,NaN,NaN,NaN,...,-36.449418,-57.768604,6238.0,Dolores,-36.449418,-57.768604,60238.0,Dolores,06,Buenos Aires
1,Facultad Latinoamericana de Ciencias Sociales,Facultad Latinoamericana de Ciencias Sociales,Tucumán 1966,NaN,"-34.6021735,-58.3972997",NaN,NaN,NaN,NaN,NaN,...,-34.602173,-58.397300,2021.0,Comuna 3,-34.602173,-58.397300,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
2,Instituto Tecnológico de Buenos Aires,Instituto Tecnológico de Buenos Aires,Av. Eduardo Madero 399,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6028340446427,-58.368183272295",NaN,NaN,NaN,NaN,NaN,...,-34.602834,-58.368183,2007.0,Comuna 1,-34.602834,-58.368183,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
3,Instituto Universitario Aeronáutico,Instituto Universitario Aeronáutico,Av. Fuerza Aerea Argentina 6500,http://apis.datos.gob.ar/georef/api/direccione...,"-31.4337174,-64.2779779",NaN,NaN,NaN,NaN,NaN,...,-31.433717,-64.277978,14014.0,Capital,-31.433717,-64.277978,140077.0,Córdoba,14,Córdoba
4,Instituto Universitario CEMIC,Instituto Universitario CEMIC,Valdenegro 4337,NaN,"-34.5547176,-58.4972877",NaN,NaN,NaN,NaN,NaN,...,-34.554718,-58.497288,2084.0,Comuna 12,-34.554718,-58.497288,NaN,NaN,02,Ciudad Autónoma de Buenos Aires

In [29]:
# chequea si hay instituciones faltantes para el merge
instituciones_en_alumnos = set(df_alumnos_merged.institucion_nombre.unique())
instituciones_en_universidades = set(df_universidades.institucion_nombre.unique())

instituciones_en_universidades - instituciones_en_alumnos

{'Instituto Universitario Aeronáutico',
 'Instituto Universitario ISEDET',
 'Instituto Universitario Nacional de Derechos Humanos "Madres de Plaza de Mayo"',
 'Instituto Universitario Nacional del Arte',
 'Instituto Universitario Naval',
 'Instituto Universitario Patagónico de las Artes',
 'Instituto Universitario River Plate',
 'Instituto Universitario de Ciencias Biomedicas de Córdoba',
 'Instituto Universitario de la Policía Federal Argentina',
 'Instituto Universitario del Ejército "Mayor Francisco Romero"',
 'Instituto Universitario del Gran Rosario',
 'Universidad Autónoma de Entre ríos',
 'Universidad Católica de las Misiones',
 'Universidad Favaloro',
 'Universidad Metropolitana para la Educación y el Trabajo',
 'Universidad Nacional José C. Paz',
 'Universidad Nacional de Entre ríos',
 'Universidad Nacional de Hurlingham',
 'Universidad Nacional de Rafaela',
 'Universidad Nacional de Tierra del Fuego, Antártida e Islas del Atlántico Sur',
 'Universidad Nacional de Villa Mercedes',
 'Universidad Nacional de las Artes',
 'Universidad Nacional de río Cuarto',
 'Universidad Nacional de río Negro',
 'Universidad Nacional del Oeste',
 'Universidad Pedagógica Nacional',
 'Universidad Popular Madres de Plaza de Mayo',
 'Universidad Provincial de Ezeiza',
 'Universidad Provincial del Sudoeste',
 'Universidad Salesiana Argentina',
 'Universidad de Congreso',
 'Universidad de San Isidro "Dr. Plácido Marín"',
 'Universidad de la Defensa Nacional',
 'Universidad de la Fraternidad de Agrupaciones Santo Tomás de Aquino',
 'Universidad del Congreso'}

In [30]:
df_universidades_merged = df_alumnos_merged.merge(df_universidades, how="left", left_on="institucion_nombre_new", right_on="institucion_nombre")
df_universidades_merged.head()

,anio,institucion_tipo,institucion_nombre_x,institucion_nombre_new,institucion_nombre_unidad_academica,unidad_academica,unidad_academica_new,carrera_nombre,carrera_titulo,institucion_gestion,...,lat,lon,departamento_id,departamento_nombre,latitud,longitud,municipio_id,municipio_nombre,provincia_id,provincia_nombre
0,2011,Universidad,Universitá Degli Studi di Bologna,Universitá Degli Studi di Bologna,Universitá Degli Studi di Bologna - Università...,Università Degli Studi di Bologna,Università Degli Studi di Bologna,Relaciones Internacionales,Magister en Relaciones Internacionales Europa ...,Privada,...,44.467909,11.295508,NaN,NaN,44.467909,11.295508,NaN,NaN,NaN,NaN
1,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Ciencia Politica,Doctor en Ciencia Politica,Privada,...,-34.547697,-58.448939,2091.0,Comuna 13,-34.547697,-58.448939,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
2,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Ciencia Politica,Licenciatura en Ciencia Politica y Gobierno,Privada,...,-34.547697,-58.448939,2091.0,Comuna 13,-34.547697,-58.448939,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
3,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Ciencia Politica,Magister en Ciencia Politica,Privada,...,-34.547697,-58.448939,2091.0,Comuna 13,-34.547697,-58.448939,NaN,NaN,02,Ciudad Autónoma de Buenos Aires
4,2011,Universidad,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella - Departamento d...,Departamento de Ciencia Politica y Estudios In...,Departamento de Ciencia Politica y Estudios In...,Relaciones Internacionales,Licenciatura en Estudios Internacionales,Privada,...,-34.547697,-58.448939,2091.0,Comuna 13,-34.547697,-58.448939,NaN,NaN,02,Ciudad Autónoma de Buenos Aires

In [31]:
df_evolucion_universidades = df_universidades_merged.groupby(["anio","provincia_id","carrera_grupo"]).sum()
df_evolucion_universidades = df_evolucion_universidades[variables]
df_evolucion_universidades = df_evolucion_universidades.reset_index()
df_evolucion_universidades.head()

,anio,provincia_id,carrera_grupo,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres
0,2011,02,Arquitectura,27066.0,13711.0,13355.0,4881.0,2347.0,2534.0,1594.0,748.0,846.0
1,2011,02,Arte,40336.0,12435.0,27901.0,8875.0,2812.0,6063.0,2156.0,559.0,1597.0
2,2011,02,Deporte,1209.0,629.0,580.0,286.0,159.0,127.0,113.0,62.0,51.0
3,2011,02,Derecho,68838.0,30178.0,38660.0,14508.0,6521.0,7987.0,6596.0,2852.0,3744.0
4,2011,02,Economicas,158727.0,78026.0,80701.0,35718.0,17676.0,18042.0,13111.0,6198.0,6913.0

In [32]:
df_evolucion_universidades["estudiantes_mujeres_pct"] = df_evolucion_universidades.estudiantes_mujeres/df_evolucion_universidades.estudiantes_total

In [33]:
estudiantes_totales = df_evolucion_universidades.groupby(["anio", 'provincia_id']).sum()["estudiantes_total"]

In [34]:
df_evolucion_universidades['estudiantes_grupo_pct'] = df_evolucion_universidades.apply(
    lambda row: row["estudiantes_total"] / estudiantes_totales[row["anio"], row["provincia_id"]],
    axis=1
)

In [35]:
df_evolucion_universidades.head()

,anio,provincia_id,carrera_grupo,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres,estudiantes_mujeres_pct,estudiantes_grupo_pct
0,2011,02,Arquitectura,27066.0,13711.0,13355.0,4881.0,2347.0,2534.0,1594.0,748.0,846.0,0.493423,0.035881
1,2011,02,Arte,40336.0,12435.0,27901.0,8875.0,2812.0,6063.0,2156.0,559.0,1597.0,0.691715,0.053473
2,2011,02,Deporte,1209.0,629.0,580.0,286.0,159.0,127.0,113.0,62.0,51.0,0.479735,0.001603
3,2011,02,Derecho,68838.0,30178.0,38660.0,14508.0,6521.0,7987.0,6596.0,2852.0,3744.0,0.561608,0.091259
4,2011,02,Economicas,158727.0,78026.0,80701.0,35718.0,17676.0,18042.0,13111.0,6198.0,6913.0,0.508426,0.210425

In [36]:
df_evolucion_universidades.to_csv("data/output/ubicacion_evolucion_genero.csv", encoding = "UTF8", index = False)

In [37]:
##ETL Markers de universidades

### Calculo indicadores por universidad-grupo carrera

In [135]:
def create_grupo_indics_str(row):
    """Crea string con variables por grupo carrera."""
    
    grupo_indics_str = "{:12}: {:5} estudiantes | {:.1%} mujeres".format(
        row["carrera_grupo"],
        int(row["estudiantes_total"]),
        row["estudiantes_mujeres_pct"],
    )
    #print(grupo_indics_str)
    return grupo_indics_str

In [136]:
# agrupo por universidad-grupo para el año 2017 (el último)
df_universidad_grupo = df_universidades_merged[df_universidades_merged.anio == 2017].groupby(
    ["institucion_nombre_new", "carrera_grupo"]
).sum()
df_universidad_grupo = df_universidad_grupo[variables]
df_universidad_grupo = df_universidad_grupo.reset_index()

# elimino agrupaciones que no tienen estudiantes
df_universidad_grupo = df_universidad_grupo[df_universidad_grupo.estudiantes_total > 0]

# creo indicadores de interés y orden por % estudiantes mujeres
df_universidad_grupo["estudiantes_mujeres_pct"] = df_universidad_grupo.estudiantes_mujeres / df_universidad_grupo.estudiantes_total
df_universidad_grupo["carrera_grupo_indics"] = df_universidad_grupo.apply(create_grupo_indics_str, axis=1)
df_universidad_grupo = df_universidad_grupo.sort_values(
    ["institucion_nombre_new", "estudiantes_mujeres_pct"],
    ascending=False
)

df_universidad_grupo.head()

,institucion_nombre_new,carrera_grupo,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres,estudiantes_mujeres_pct,carrera_grupo_indics
746,Universidad del Salvador,Idiomas,80.0,9.0,71.0,24.0,5.0,19.0,0.0,0.0,0.0,0.887500,Idiomas : 80 estudiantes | 88.8% mujeres
750,Universidad del Salvador,Salud,204.0,23.0,181.0,58.0,10.0,48.0,2.0,0.0,2.0,0.887255,Salud : 204 estudiantes | 88.7% mujeres
745,Universidad del Salvador,Educación,1335.0,305.0,1030.0,439.0,96.0,343.0,73.0,22.0,51.0,0.771536,Educación : 1335 estudiantes | 77.2% mujeres
751,Universidad del Salvador,Sociales,1437.0,466.0,971.0,246.0,82.0,164.0,23.0,4.0,19.0,0.675713,Sociales : 1437 estudiantes | 67.6% mujeres
748,Universidad del Salvador,Naturales,228.0,81.0,147.0,32.0,8.0,24.0,3.0,1.0,2.0,0.644737,Naturales : 228 estudiantes | 64.5% mujeres

In [137]:
def concatenate_map(grupos_carreras):
    grupos_str = [str(grupo) for grupo in grupos_carreras if pd.notnull(grupo)]
    return ",".join(grupos_str)

In [138]:
df_universidad_grupo.groupby("institucion_nombre_new").sum()

,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres,estudiantes_mujeres_pct
institucion_nombre_new,,,,,,,,,,
Facultad Latinoamericana de Ciencias Sociales,893.0,274.0,619.0,268.0,79.0,189.0,124.0,29.0,95.0,2.765787
Instituto Tecnológico de Buenos Aires,6109.0,4911.0,1198.0,563.0,426.0,137.0,591.0,449.0,142.0,2.317069
Instituto Universitario CEMIC,25.0,4.0,21.0,13.0,2.0,11.0,0.0,0.0,0.0,0.840000
Instituto Universitario Escuela Argentina de Negocios,666.0,352.0,314.0,268.0,133.0,135.0,95.0,56.0,39.0,0.471471
Instituto Universitario Escuela Superior de Economía y Administración de Empresas,118.0,67.0,51.0,47.0,28.0,19.0,4.0,3.0,1.0,0.432203
Instituto Universitario Escuela de Medicina del Hospital Italiano,138.0,65.0,73.0,64.0,29.0,35.0,3.0,1.0,2.0,1.064326
Instituto Universitario Italiano de Rosario,100.0,27.0,73.0,12.0,2.0,10.0,3.0,0.0,3.0,0.730000
Instituto Universitario de Ciencias de la Salud de la Fundación Barceló,174.0,75.0,99.0,25.0,13.0,12.0,8.0,3.0,5.0,0.568966
Instituto Universitario de Salud Mental de la Asociación Psicoanalítica de Buenos Aires,54.0,44.0,10.0,11.0,3.0,8.0,1.0,1.0,0.0,0.666667
Pontificia Universidad Católica Argentina Santa María de los Buenos Aires,8986.0,4483.0,4503.0,2203.0,1086.0,1117.0,966.0,511.0,455.0,4.824192
Universidad Abierta Interamericana,8370.0,5054.0,3316.0,1689.0,981.0,708.0,1405.0,849.0,556.0,5.408971
Universidad Adventista del Plata,614.0,406.0,208.0,190.0,140.0,50.0,46.0,17.0,29.0,2.439909
Universidad Argentina John F. Kennedy,2678.0,1528.0,1150.0,788.0,357.0,431.0,326.0,159.0,167.0,4.512998
Universidad Argentina de la Empresa,19956.0,11518.0,8438.0,4671.0,2703.0,1968.0,1893.0,989.0,904.0,3.790048
Universidad Atlántida Argentina,901.0,518.0,383.0,287.0,196.0,91.0,46.0,21.0,25.0,1.348828
Universidad Austral,3104.0,1748.0,1356.0,726.0,395.0,331.0,264.0,149.0,115.0,2.885936
Universidad Autónoma de Entre Ríos,6939.0,3157.0,3782.0,1784.0,829.0,955.0,256.0,105.0,151.0,3.855587
Universidad Blas Pascal,5784.0,2436.0,3348.0,1971.0,819.0,1152.0,367.0,134.0,233.0,3.658710
Universidad CAECE,1754.0,1069.0,685.0,373.0,212.0,161.0,165.0,104.0,61.0,2.224926
Universidad Católica de Cuyo,2523.0,1188.0,1335.0,570.0,305.0,265.0,263.0,118.0,145.0,2.987992
Universidad Católica de Córdoba,3687.0,1812.0,1875.0,881.0,422.0,459.0,460.0,193.0,267.0,5.296824
Universidad Católica de La Plata,3354.0,1635.0,1719.0,590.0,312.0,278.0,269.0,121.0,148.0,4.704617
Universidad Católica de Salta,13930.0,6099.0,7831.0,2607.0,1121.0,1486.0,768.0,330.0,438.0,5.074299
Universidad Católica de Santa Fe,2719.0,1334.0,1385.0,396.0,187.0,209.0,264.0,159.0,105.0,6.195925
Universidad Católica de Santiago del Estero,4228.0,2013.0,2215.0,822.0,386.0,436.0,300.0,146.0,154.0,3.102636
Universidad Champagnat,1270.0,596.0,674.0,192.0,96.0,96.0,176.0,75.0,101.0,2.370406
Universidad Empresarial Siglo 21,45154.0,22123.0,23031.0,18192.0,8999.0,9193.0,2881.0,1170.0,1711.0,4.243717
Universidad Favaloro,339.0,123.0,216.0,73.0,23.0,50.0,44.0,17.0,27.0,1.140483
Universidad Gastón Dachary,1583.0,1088.0,495.0,369.0,266.0,103.0,63.0,37.0,26.0,1.359752
Universidad ISALUD,586.0,241.0,345.0,251.0,96.0,155.0,69.0,24.0,45.0,1.981448
...,...,...,...,...,...,...,...,...,...,...
Universidad Nacional del Centro de la Provincia de Buenos Aires,8448.0,4520.0,3928.0,1687.0,859.0,828.0,303.0,166.0,137.0,5.524551
Universidad Nacional del Chaco Austral,6056.0,3033.0,3023.0,3683.0,1764.0,1919.0,30.0,20.0,10.0,3.228205
Universidad Nacional del Comahue,13451.0,5829.0,7622.0,3421.0,1600.0,1821.0,625.0,223.0,402.0,6.076457
Universidad Nacional del Litoral,25610.0,11793.0,13817.0,5544.0,2483.0,3061.0,1206.0,514.0,692.0,6.600571
Universidad Nacional del Nordeste,29137.0,13653.0,15484.0,6422.0,3074.0,3348.0,2025.0,742.0,1283.0,6.596719
Universidad Nacional del Noroeste de la Provincia de Buenos Aires,3761.0,2188.0,1573.0,1101.0,594.0,507.0,163.0,89.0,74.0,4.088958
Universidad Nacional del Sur,12470.0,6287.0,6183.0,3108.0,1599.0,1509.0,574.0,253.0,321.0,6.236875
Universidad Notarial Argentina,74.0,22.0,52.0,36.0,9.0,27.0,2.0,0.0,2.0,0.702703
Universidad Tecnológica Nacional,88627.0,71043.0,17584.0,17127.0,13579.0,3548.0,3334.0,2530.0,804.0,3.589262
Universidad Torcuato Di Tella,4547.0,2429.0,2118.0,1142.0,593.0,549.0,445.0,240.0,205.0,2.853347
Universidad de Belgrano,7346.0,4267.0,3079.0,1966.0,1100.0,866.0,672.0,357.0,315.0,3.513274
Universidad de Buenos Aires,146858.0,69412.0,77446.0,30801.0,15289.0,15512.0,9110.0,3773.0,5337.0,8.220425
Universidad de Ciencias Empresariales y Sociales,7009.0,3308.0,3701.0,2250.0,1053.0,1197.0,657.0,232.0,425.0,2.995543
Universidad de Concepción del Uruguay,740.0,335.0,405.0,88.0,47.0,41.0,78.0,25.0,53.0,1.533220
Universidad de Flores,951.0,527.0,424.0,176.0,107.0,69.0,100.0,59.0,41.0,1.780641
Universidad de Mendoza,5002.0,2493.0,2509.0,1167.0,612.0,555.0,399.0,169.0,230.0,3.731024
Universidad de Morón,8458.0,4416.0,4042.0,1933.0,1026.0,907.0,1160.0,598.0,562.0,6.586302
Universidad de Palermo,6891.0,3303.0,3588.0,2298.0,1125.0,1173.0,655.0,236.0,419.0,4.787211
Universidad de San Andrés,1386.0,757.0,629.0,536.0,313.0,223.0,370.0,204.0,166.0,2.673262
Universidad de la Cuenca del Plata,2396.0,1114.0,1282.0,463.0,242.0,221.0,100.0,34.0,66.0,4.115539
Universidad de la Fraternidad de Agrupaciones Santo Tomás de Aquino,4214.0,2392.0,1822.0,1525.0,848.0,677.0,347.0,217.0,130.0,3.951147
Universidad de la Marina Mercante,2096.0,1244.0,852.0,410.0,226.0,184.0,213.0,117.0,96.0,1.808632
Universidad del Aconcagua,2318.0,1053.0,1265.0,549.0,270.0,279.0,157.0,56.0,101.0,3.647522
Universidad del CEMA,1007.0,727.0,280.0,258.0,171.0,87.0,176.0,122.0,54.0,1.954697
Universidad del Centro Educativo Latinoamericano,1260.0,686.0,574.0,277.0,151.0,126.0,76.0,39.0,37.0,1.632764
Universidad del Cine,24.0,13.0,11.0,11.0,6.0,5.0,3.0,3.0,0.0,0.458333
Universidad del Este,539.0,196.0,343.0,197.0,68.0,129.0,85.0,31.0,54.0,2.623659
Universidad del Museo Social Argentino,1121.0,394.0,727.0,284.0,94.0,190.0,119.0,47.0,72.0,4.429005
Universidad del Norte Santo Tomás de Aquino,2444.0,1160.0,1284.0,691.0,342.0,349.0,281.0,103.0,178.0,3.292795
Universidad del Salvador,9157.0,4145.0,5012.0,1770.0,750.0,1020.0,253.0,111.0,142.0,6.405749

In [139]:
serie_lista_grupos = df_universidad_grupo.groupby("institucion_nombre_new")["carrera_grupo_indics"].apply(
    concatenate_map)
df_universidad_indicadores = df_universidad_grupo.groupby("institucion_nombre_new").sum()
df_universidad_indicadores["estudiantes_mujeres_pct"] = df_universidad_indicadores.estudiantes_mujeres / df_universidad_indicadores.estudiantes_total
#serie_lista_carrera = df_universidades_merged.groupby("institucion_nombre_new")["carrera_nombre"].apply(
#    concatenate_map)

In [143]:
df_ubicacion_universidades_grupos = df_universidades.merge(
    serie_lista_grupos, how="left", left_on="institucion_nombre", right_index=True)
df_ubicacion_universidades_grupos = df_ubicacion_universidades_grupos.merge(
    df_universidad_indicadores, how="left", left_on="institucion_nombre", right_index=True)

#df_ubicacion_universidades_grupos = df_ubicacion_universidades_grupos.merge(
#    serie_lista_carrera, how="left", left_on="institucion_nombre", right_index=True)

In [144]:
df_ubicacion_universidades_grupos.to_csv("data/output/universidades_mapa.csv", encoding = "UTF8", index = False)
#tasas de egresos pero no lineamente, buscar la formula, estandariza el año de duracion.

In [145]:
df_ubicacion_universidades_grupos

,universidad_nombre,institucion_nombre,institucion_direccion,api,coordenadas,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres,estudiantes_mujeres_pct
0,Escuela Universitaria de Teologia,Escuela Universitaria de Teologia,Pasaje Catedral 1750,NaN,"-36.4494181,-57.7686044",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Facultad Latinoamericana de Ciencias Sociales,Facultad Latinoamericana de Ciencias Sociales,Tucumán 1966,NaN,"-34.6021735,-58.3972997",NaN,NaN,NaN,NaN,NaN,...,893.0,274.0,619.0,268.0,79.0,189.0,124.0,29.0,95.0,0.693169
2,Instituto Tecnológico de Buenos Aires,Instituto Tecnológico de Buenos Aires,Av. Eduardo Madero 399,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6028340446427,-58.368183272295",NaN,NaN,NaN,NaN,NaN,...,6109.0,4911.0,1198.0,563.0,426.0,137.0,591.0,449.0,142.0,0.196104
3,Instituto Universitario Aeronáutico,Instituto Universitario Aeronáutico,Av. Fuerza Aerea Argentina 6500,http://apis.datos.gob.ar/georef/api/direccione...,"-31.4337174,-64.2779779",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Instituto Universitario CEMIC,Instituto Universitario CEMIC,Valdenegro 4337,NaN,"-34.5547176,-58.4972877",NaN,NaN,NaN,NaN,NaN,...,25.0,4.0,21.0,13.0,2.0,11.0,0.0,0.0,0.0,0.840000
5,Instituto Universitario de Ciencias Biomedicas...,Instituto Universitario de Ciencias Biomedicas...,Naciones Unidas 400-440,NaN,"-31.4421202,-64.2033758",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Instituto Universitario de Ciencias de la Salu...,Instituto Universitario de Ciencias de la Salu...,Av. Gral. Las Heras 1907,NaN,"-34.5951617,-58.4021427",NaN,NaN,NaN,NaN,NaN,...,174.0,75.0,99.0,25.0,13.0,12.0,8.0,3.0,5.0,0.568966
7,Instituto Universitario de Gendarmeria Nacional,Instituto Universitario de Gendarmeria Nacional,Av. Paseo Colón 533,NaN,"-34.6142528,-58.371724",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Instituto Universitario de la Policía Federal ...,Instituto Universitario de la Policía Federal ...,Rosario 532,NaN,"-34.6196133,-58.4382653",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Instituto Universitario de Salud Mental de la ...,Instituto Universitario de Salud Mental de la ...,Báez 248,NaN,"-34.567895,-58.4361568",NaN,NaN,NaN,NaN,NaN,...,54.0,44.0,10.0,11.0,3.0,8.0,1.0,1.0,0.0,0.185185
10,Instituto Universitario de Seguridad Marítima,Instituto Universitario de Seguridad Marítima,Av. Corrientes 345,NaN,"-34.6030978,-58.3739408",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Instituto Universitario del Ejército ""Mayor Fr...","Instituto Universitario del Ejército ""Mayor Fr...",Av. Cabildo 65,http://apis.datos.gob.ar/georef/api/direccione...,"-34.57439170160686,-58.43650022052455",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Instituto Universitario del Gran Rosario,Instituto Universitario del Gran Rosario,Corrientes 1254,NaN,"-32.9512965,-60.6460659",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Instituto Universitario Escuela Argentina de N...,Instituto Universitario Escuela Argentina de N...,Av. Córdoba 1690,NaN,"-34.5997447,-58.3934405",NaN,NaN,NaN,NaN,NaN,...,666.0,352.0,314.0,268.0,133.0,135.0,95.0,56.0,39.0,0.471471
14,Instituto Universitario Escuela de Medicina de...,Instituto Universitario Escuela de Medicina de...,Potosí 4265,NaN,"-34.6071979,-58.4291149",NaN,NaN,NaN,NaN,NaN,...,138.0,65.0,73.0,64.0,29.0,35.0,3.0,1.0,2.0,0.528986
15,Instituto Universitario Escuela Superior de Ec...,Instituto Universitario Escuela Superior de Ec...,Uriarte 2472,NaN,"-34.5809241,-58.4253568",NaN,NaN,NaN,NaN,NaN,...,118.0,67.0,51.0,47.0,28.0,19.0,4.0,3.0,1.0,0.432203
16,Instituto Universitario ISEDET,Instituto Universitario ISEDET,Camacuá 282,NaN,"-34.6307959,-58.4656187",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Instituto Universitario Italiano de Rosario,Instituto Universitario Italiano de Rosario,Crespo 843,NaN,"-32.9415838,-60.6705633",NaN,NaN,NaN,NaN,NaN,...,100.0,27.0,73.0,12.0,2.0,10.0,3.0,0.0,3.0,0.730000
18,Instituto Universitario Nacional de Derechos H...,Instituto Universitario Nacional de Derechos H...,Av. Pueyrredón 19,NaN,"-34.6097284,-58.4079993",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Instituto Universitario Nacional del Arte,Instituto Universitario Nacional del Arte,Azcuénaga 1129,NaN,"-34.5946906,-58.4018519",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Instituto Universitario Naval,Instituto Universitario Naval,Francisco Narciso de Laprida 555,NaN,"-34.5945248,-58.469703",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Instituto Universitario Patagónico de las Artes,Instituto Universitario Patagónico de las Artes,"Rivadavia 2263,",NaN,"-39.0178878,-67.5960898",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Instituto Universitario River Plate,Instituto Universitario River Plate,Av. Pres. Figueroa Alcorta 7597,NaN,"-34.5453018,-58.4519636",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Pontificia Universidad Católica Argentina Sant...,Pontificia Universidad Católica Argentina Sant...,AvENIDA Alicia Moreau de Justo 1600,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6148453,-58.3668853",NaN,NaN,NaN,NaN,NaN,...,8986.0,4483.0,4503.0,2203.0,1086.0,1117.0,966.0,511.0,455.0,0.501113
24,Universidad Favaloro,Universidad Favaloro,Av. Entre Ríos 495,NaN,"-34.6148113,-58.3940258",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Universidad Abierta Interamericana,Universidad Abierta Interamericana,Av. San Juan 951,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6221199173329, -58.379325181549746",NaN,NaN,NaN,NaN,NaN,...,8370.0,5054.0,3316.0,1689.0,981.0,708.0,1405.0,849.0,556.0,0.396177
26,Universidad Adventista del Plata,Universidad Adventista del Plata,25 de mayo 99,http://apis.datos.gob.ar/georef/api/direccione...,"-32.0759594,-60.4665987",NaN,NaN,NaN,NaN,NaN,...,614.0,406.0,208.0,190.0,140.0,50.0,46.0,17.0,29.0,0.338762
27,Universidad Argentina de la Empresa,Universidad Argentina de la Empresa,Lima 775,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6173746323554,-58.381525671564",NaN,NaN,NaN,NaN,NaN,...,19956.0,11518.0,8438.0,4671.0,2703.0,1968.0,1893.0,989.0,904.0,0.422830
28,Universidad Argentina John F. Kennedy,Universidad Argentina John F. Kennedy,Bartolomé Mitre 1411,http://apis.datos.gob.ar/georef/api/direccione...,"-34.60762266844467,-58.38645625343852",NaN,NaN,NaN,NaN,NaN,...,2678.0,1528.0,1150.0,788.0,357.0,431.0,326.0,159.0,167.0,0.429425
29,Universidad Atlántida Argentina,Universidad Atlántida Argentina,Belgrano 89,http://apis.datos.gob.ar/georef/api/direccione...,"-37.1552476,-57.7427199",NaN,NaN,NaN,NaN,NaN,...,901.0,518.0,383.0,287.0,196.0,91.0,46.0,21.0,25.0,0.425083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,Universidad Nacional de río Negro,Universidad Nacional de río Negro,Don Bosco 500,http://apis.datos.gob.ar/georef/api/direccione...,"-39.0279881065646, -67.58044691129079",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Universidad Nacional de Rosario,Universidad Nacional de Rosario,Maipú 1065,http://apis.datos.gob.ar/georef/api/direccione...,"-32.950309649805945,-60.636126952347716",NaN,NaN,NaN,NaN,NaN,...,42019.0,18604.0,23415.0,7070.0,3224.0,3846.0,2394.0,837.0,1557.0,0.557248
102,Universidad Nacional de Salta,Universidad Nacional de Salta,Av Bolivia 5150,http://apis.datos.gob.ar/georef/api/direccione...,"-24.7280281,-65.4114867",NaN,NaN,NaN,NaN,NaN,...,13964.0,6492.0,7472.0,3109.0,1509.0,1600.0,232.0,112.0,120.0,0.535090
103,Universidad Nacional de San Juan,Universidad Nacional de San Juan,Mitre 396,http://apis.datos.gob.ar/georef/api/direccione...,"-31.5354691,-68.5412352,15",NaN,NaN,NaN,NaN,NaN,...,14058.0,6877.0,7181.0,2940.0,1533.0,1407.0,408.0,190.0,218.0,0.510812
104,Universidad Nacional de San Luis,Universidad Nacional de San Luis,Ejército de los Andes 950,http://apis.datos.gob.ar/georef/api/direccione...,"-33.2962223,-66.3441194",NaN,NaN,NaN,NaN,NaN,...,5092.0,2128.0,2964.0,1293.0,490.0,803.0,216.0,75.0,141.0,0.582090
105,Universidad Nacional de San Martín,Universidad Nacional de San Martín,Ramsay 2250,http://apis.datos.gob.ar/georef/api/direccione...,"-34.550664100769964,-58.441134539431594",NaN,NaN,NaN,NaN,NaN,...,8610.0,3601.0,5009.0,2234.0,904.0,1330.0,584.0,149.0,435.0,0.581765
106,Universidad Nacional de Santiago del Estero,Universidad Nacional de Santiago del Estero,Avenida Belgrano Sur 1912,http://apis.datos.gob.ar/georef/api/direccione...,"-27.8014246,-64.2531763",NaN,NaN,NaN,NaN,NaN,...,10589.0,3339.0,7250.0,2921.0,829.0,2092.0,319.0,78.0,241.0,0.684673
107,"Universidad Nacional de Tierra del Fuego, Antá...","Universidad Nacional de Tierra del Fuego, Antá...",Fuegia Basket 251,http://apis.datos.gob.ar/georef/api/direccione...,"-54.81888630058655, -68.32552591092275",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,Universidad Nacional de Tres de Febrero,Universidad Nacional de Tres de Febrero,Av. Gral. Mosconi 2736,http://apis.datos.gob.ar/georef/api/direccione...,"-34.6050318,-58.5665275",NaN,NaN,NaN,NaN,NaN,...,7650.0,3818.0,3832.0,2061.0,957.0,1104.0,254.0,114.0,140.0,0.500915
109,Universidad Nacional de Tucumán,Universidad Nacional de Tucumán,Batalla de Ayacucho 491,http://apis.datos.gob.ar/georef/api/direccione...,"-26.8363912,-65.2133295",NaN,NaN,NaN,NaN,NaN,...,28795.0,12864.0,15931.0,6219.0,2661.0,3558.0,1458.0,574.0,884.0,0.553256
110,Universidad Nacional de Villa María,Universidad Nacional de Villa María,Arturo Jauretche 1555,http://apis.datos.gob.ar/georef/api/direccione...,"-32.3995102,-63.2651483",NaN,NaN,NaN,NaN,NaN,...,3155.0,1510.0,1645.0,1273.0,698.0,575.0,84.0,30.0,54.0,0.521395
111,Universidad Nacional de Villa Mercedes,Universidad Nacional de Villa Mercedes,Las Heras 383,http://apis.datos.gob.ar/georef/api/direccione...,"-33.6865689,-65.4698988",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Universidad Nacional del Centro de la Provinci...,Universidad Nacional del Centro de la Provinci...,Pinto 399,http://apis.datos.gob.ar/georef/api/direccione...,"-37.3285417102325,-59.1380501689951",NaN,NaN,NaN,NaN,NaN,...,8448.0,4520.0,3928.0,1687.0,859.0,828.0,303.0,166.0,137.0,0.464962
113,Universidad Nacional del Chaco Austral,Universidad Nacional del Chaco Austral,Fernández 755,http://apis.datos.gob.ar/georef/api/direccione...,"-26.8017124,-60.4491146",NaN,NaN,NaN,NaN,NaN,...,6056.0,3033.0,3023.0,3683.0,1764.0,1919.0,30.0,20.0,10.0,0.499174
114,Universidad Nacional del Comahue,Universidad Nacional del Comahue,Av. Santa Fe 1845,http://apis.datos.gob.ar/georef/api/direccione...,"-34.59583822943477,-58.393932130303796",NaN,NaN,NaN,NaN,NaN,...,13451.0,5829.0,7622.0,3421.0,1600.0,1821.0,625.0,223.0,402.0,0.566649
115,Universidad Nacional del Litoral,Universidad Nacional del Litoral,San Jerónimo 3231,http://apis.datos.gob.ar/georef/api/direccione...,"-31.638260020689607, -60.70559340518095",NaN,NaN,NaN,NaN,NaN,...,25610.0,11793.0,13817.0,5544.0,2483.0,3061.0,1206.0,514.0,692.0,0.539516
116,Universidad Nacional del Nordeste,Universidad Nacional del Nordeste,25 de mayo 868,http://apis.datos.gob.ar/georef/api/direccione...,"-27.4607657,-58.9542543",NaN,NaN,NaN,NaN,NaN,...,29137.0,13653.0,15484.0,6422.0,3074.0,3348.0,2025.0,742.0,1283.0,0.531421
117,Universidad Nacional del Noroeste de la Provin...,Universidad Nacional del Noroeste de la Provin...,Roque Saenz Peña 456,http://apis.datos.gob.ar/georef/api/direccione...,"-34.861684718919854, -61.52755638690734",NaN,NaN,NaN,NaN,NaN,...,3761.0,2188.0,1573.0,1101.0,594.0,507.0,163.0,89.0,74.0,0.418240
118,Universidad Nacional del Oeste,Universidad Nacional del Oeste,Gral. Manuel Belgrano 369,http://apis.datos.gob.ar/georef/api/direccione...,"-34.65254628739099,-58.62119862036371",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,Universidad Nacional del Sur,Universidad Nacional del Sur,Av. Alem 1253,http://apis.datos.gob.ar/georef/api/direccione...,"-38.67866305629395,-62.29611089500422",NaN,NaN,NaN,NaN,NaN,...,12470.0,6287.0,6183.0,3108.0,1599.0,1509.0,574.0,253.0,321.0,0.495830
120,Universidad Nacional José C. Paz,Universidad Nacional José C. Paz,Leandro N. Alem 4731,http://apis.datos.gob.ar/georef/api/direccione...,"-34.521483660692496,-58.745796901146605",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,Universidad Notarial Argentina,Universidad Notarial Argentina,Av. 51 435,NaN,"-34.750524,-58.308108",NaN,NaN,NaN,NaN,NaN,...,74.0,22.0,52.0,36.0,9.0,27.0,2.0,0.0,2.0,0.702703
122,Universidad Pedagógica Nacional,Universidad Pedagógica Nacional,Piedras 1080,NaN,"-34.61955811945053,-58.37559426109925",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Universidad Popular Madres de Plaza de Mayo,Universidad Popular Madres de Plaza de Mayo,Av. Hipólito Yrigoyen 1584,NaN,"-34.6100495,-58.3908878",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,Universidad Provincial de Ezeiza,Universidad Provincial de Ezeiza,Alfonsina Storni 41,NaN,"-34.7895235,-58.5231426",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Universidad Provincial del Sudoeste,Universidad Provincial del Sudoeste,Cd. de Cali 320,NaN,"-36.6196788,-62.5506754",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,Universidad Salesiana Argentina,Universidad Salesiana Argentina,Gorriti 1249,NaN,"-38.7225345,-62.282452",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,Universidad Tecnológica Nacional,Universidad Tecnológica Nacional,Sarmiento 440,http://apis.datos.gob.ar/georef/api/direccione...,"-34.61847060349939,-58.45044388901235",NaN,NaN,NaN,NaN,NaN,...,88627.0,71043.0,17584.0,17127.0,13579.0,3548.0,3334.0,2530.0,804.0,0.198405
128,Universidad Torcuato Di Tella,Universidad Torcuato Di Tella,Av. Pres. Figueroa Alcorta 7350,NaN,"-34.5476972,-58.4489394",NaN,NaN,NaN,NaN,NaN,...,4547.0,2429.0,2118.0,1142.0,593.0,549.0,445.0,240.0,205.0,0.465802
129,Universitá Degli Studi di Bologna,Universitá Degli Studi di Bologna,"Via Zamboni, 33",NaN,"44.4679091,11.2955076,12",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN